- name: restart systemd-resolved
  become: true
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: restart docker
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted